// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM14L1F6QCDAVCfUZkB7BJ4nT9jHYGus8',
    appId: '1:372804098657:web:eaaeae85591f32e1506820',
    messagingSenderId: '372804098657',
    projectId: 'netflix-clone-test-a710e',
    authDomain: 'netflix-clone-test-a710e.firebaseapp.com',
    storageBucket: 'netflix-clone-test-a710e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxubafSTylqiFreeTReba1O9FzEdVvT24',
    appId: '1:372804098657:android:551ddeeeb68ade3e506820',
    messagingSenderId: '372804098657',
    projectId: 'netflix-clone-test-a710e',
    storageBucket: 'netflix-clone-test-a710e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDx2J5013J1KKlUNbkVIkOujFyZNzM_jmY',
    appId: '1:372804098657:ios:5ccc7f97348df003506820',
    messagingSenderId: '372804098657',
    projectId: 'netflix-clone-test-a710e',
    storageBucket: 'netflix-clone-test-a710e.appspot.com',
    iosClientId: '372804098657-ct62v87f6c8703b7bqf3pcv29oh3jtqf.apps.googleusercontent.com',
    iosBundleId: 'com.example.netflix',
  );
}
